name: Deploy static content to Pages

on:
  push:
    branches: ["gh-pages"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '24.0.2'
      
      - name: Install dependencies
        run: npm install

      # Altough Vite has a built-in system to read .env[.mode] files, GitHub
      # allows to specify environment variables in the settings. It wouldn't
      # be of any advantage to create an .env file at build-time, so write
      # environment variable exports to $GITHUB_ENV instead. 
      - name: Setup Environment
        env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          BASE_PATH=/${GITHUB_REPOSITORY##*/}/
          OPEN_SOURCE_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          
          echo BASE_PATH: $BASE_PATH
          echo OPEN_SOURCE_URL: $OPEN_SOURCE_URL
          
          echo "BASE_PATH=$BASE_PATH" >> $GITHUB_ENV
          echo "OPEN_SOURCE_URL=$OPEN_SOURCE_URL" >> $GITHUB_ENV
      
      - name: Build
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
            enablement: true
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
